definitions = {"ArithmeticException": "Arithmetic error, such as divide-by-zero",
               "ArrayIndexOutOfBoundsException": "Array index is out-of-bounds",
               "ArrayStoreException": "Assignment to an array element of an incompatible type",
               "ClassCastException": "Invalid cast",
               "EnumConstantNotPresentException": "An attempt is made to use an undefined enumeration value",
               "IllegalArgumentException": "Illegal argument used to invoke a method",
               "IllegalMonitorStateException": "Illegal monitor operation, such as waiting on an unlocked thread",
               "IllegalStateException": "Environment or application is in incorrect state",
               "IllegalThreadStateException": "Requested operation not compatible with current thread state",
               "IndexOutOfBoundsException": "Some type of index is out-of-bounds",
               "NegativeArraySizeException": "Array created with a negative size",
               "NullPointerException": "Invalid use of a null reference",
               "NumberFormatException": "Invalid conversion of a string to a numeric format",
               "SecurityException": "Attempt to violate security",
               "StringIndexOutOfBounds": "Attempt to index outside the bounds of a string",
               "TypeNotPresentException": "Type not found",
               "UnsupportedOperationException": "An unsupported operation was encountered"}

keywords = {"ArithmeticException": ["arithmetic", "error", "divide-by-zero", "divide by zero"],
            "ArrayIndexOutOfBoundsException": ["array", "index", "out-of-bounds", "out", "bounds"],
            "ArrayStoreException": ["assignment", "array", "element", "incompatible type"],
            "ClassCastException": ["invalid", "cast"],
            "EnumConstantNotPresentException": ["attempt", "undefined", "enumeration value"],
            "IllegalArgumentException": ["illegal argument", "illegal", "argument", "invoke a method", "invoke"],
            "IllegalMonitorStateException": ["illegal monitor operation", "monitor", "illegal", "operation",
                                             "unlocked", "thread"],
            "IllegalStateException": ["environment", "application", "incorrect state", "incorrect"],
            "IllegalThreadStateException": ["not compatible", "current thread state", "thread"],
            "IndexOutOfBoundsException": ["index", "out-of-bounds", "out of bounds"],
            "NegativeArraySizeException": ["array created", "negative size", "array", "negative"],
            "NullPointerException": ["invalid use" "null reference"],
            "NumberFormatException": ["invalid conversion", "string", "numeric format", "numeric"],
            "SecurityException": ["violate", "security"],
            "StringIndexOutOfBounds": ["index", "outside", "bounds", "string"],
            "TypeNotPresentException": ["type", "not", "found"],
            "UnsupportedOperationException": ["unsupported", "operation", "encountered"]}
